### ISSUE TITLE
Is there somewhere where a demo of the organization chart can be viewed?

### ISSUE THREAD

**Issue by oferRounds** [AAChartModel/AAChartKit-Swift-Pro#1]
Looking for this for both iOS and Android

**Comment by oferRounds** [comment]
@AAChartModel

**Comment by AAChartModel** [comment]
You can find it in the [AAChartKit-Swift-Pro](https://github.com/AAChartModel/AAChartKit-Swift-Pro) demo now

**Comment by oferRounds** [comment]
Thank you @AAChartModel! Will you be able to add some gifs/screenshots?
