### ISSUE TITLE
在xcode15中报错Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by Maxcucurbit** [AAChartModel/AAChartKit-Swift-Pro#5]
大佬，在Xcode15,swift5.9环境下报错：Stored properties cannot be marked unavailable with '@available'
这个怎么解决，要一个个的去删除吗？

**Comment by AAChartModel** [comment]
参考: 
* https://github.com/AAChartModel/AAChartKit-Swift/pull/459

直接将报错的部分删除掉就行了

**Comment by Maxcucurbit** [comment]
/

> 参考:
> 
> * [upgrade to Xcode 15 AAChartKit-Swift#459](https://github.com/AAChartModel/AAChartKit-Swift/pull/459)
> 
> 直接将报错的部分删除掉就行了

收到，谢谢
