### ISSUE TITLE
xrange类型图表可以自定义x轴坐标和tooltip内容吗？

### ISSUE THREAD

**Issue by LoseRecall** [AAChartModel/AAChartKit-Swift-Pro#7]
tooltip显示起始时间，x轴有对应时间坐标，可以实现吗？大佬！

**Comment by AAChartModel** [comment]
有设计稿吗?

**Comment by LoseRecall** [comment]
类似这种
<img width="444" alt="企业微信20240515-113245@2x" src="https://github.com/AAChartModel/AAChartKit-Swift-Pro/assets/19203105/f971f47a-d1b4-47e7-8cae-70228914d5e4">

**Comment by AAChartModel** [comment]
另外, 参考这个相关提问:
* https://github.com/AAChartModel/AAChartKit-Swift/issues/372

你甚至可以直接通过 iOS 的原生代码, 自己绘制 `crosshair 准星线`和 `tooltip 浮动提示框`. 

如果你的自定义效果比较**特殊**或**复杂**的话, 可以使用这个方法. 简单一点的话, 上面的那种方法就基本满足需求了.

**Comment by AAChartModel** [comment]
另外参考相关问题:
* https://github.com/AAChartModel/AAChartKit/issues/1033
